def abcd(n):
    l = len(n)
    print("String Is =",n)
    print("Length Of String =",l)
    print("Total No of A =", n.count('a') + n.count('A'))
    print("Total No of B =", n.count('b') + n.count('B'))
    print("Total No of C =", n.count('c') + n.count('C'))
    print("Total No of D =", n.count('d') + n.count('D'))
    print("Total No of E =", n.count('e') + n.count('E'))
    print("Total No of F =", n.count('f') + n.count('F'))
    print("Total No of G =", n.count('g') + n.count('G'))
    print("Total No of H =", n.count('h') + n.count('H'))
    print("Total No of I =", n.count('i') + n.count('I'))
    print("Total No of J =", n.count('j') + n.count('J'))
    print("Total No of K =", n.count('k') + n.count('K'))
    print("Total No of L =", n.count('l') + n.count('L'))
    print("Total No of M =", n.count('m') + n.count('M'))
    print("Total No of N =", n.count('n') + n.count('N'))
    print("Total No of O =", n.count('o') + n.count('O'))
    print("Total No of P =", n.count('p') + n.count('P'))
    print("Total No of Q =", n.count('q') + n.count('Q'))
    print("Total No of R =", n.count('r') + n.count('R'))
    print("Total No of S =", n.count('s') + n.count('S'))
    print("Total No of T =", n.count('t') + n.count('T'))
    print("Total No of U =", n.count('u') + n.count('U'))
    print("Total No of V =", n.count('v') + n.count('V'))
    print("Total No of W =", n.count('w') + n.count('W'))
    print("Total No of X =", n.count('x') + n.count('X'))
    print("Total No of Y =", n.count('y') + n.count('Y'))
    print("Total No of Z =", n.count('z') + n.count('Z'))
print("Enter Your String")
n = str(input())
abcd(n)
